[package]
name = "neucalc"
version = "0.1.1"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4.4", features = [] }
num-integer = "0.1.45"
lazy_static = "1.4.0"
num-traits = "0.2.16"